language: python
cache: pip
python:
  # see https://docs.travis-ci.com/user/languages/python/ for options
  - "nightly"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install flake8"
  - "pip install git+https://github.com/PyCQA/pyflakes.git"
  - "pip install pytest pytest-mock"
# command to run tests
script:
  - "./run_tests.sh"
notifications:
  email: false
